import { pgTable, serial, integer, text, timestamp, boolean, real } from "drizzle-orm/pg-core";

export const subscriptionsTable = pgTable("subscriptions", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull(),
  plan: text("plan").notNull().default("starter"),
  status: text("status").notNull().default("inactive"),
  amount: real("amount").notNull().default(0),
  currency: text("currency").notNull().default("TRY"),
  interval: text("interval").notNull().default("monthly"),
  startedAt: timestamp("started_at", { withTimezone: true }),
  expiresAt: timestamp("expires_at", { withTimezone: true }),
  nextPaymentAt: timestamp("next_payment_at", { withTimezone: true }),
  cancelledAt: timestamp("cancelled_at", { withTimezone: true }),
  paynetCardOwnerId: text("paynet_card_owner_id"),
  paynetSubscriptionId: text("paynet_subscription_id"),
  cardMasked: text("card_masked"),
  cardHolder: text("card_holder"),
  autoRenew: boolean("auto_renew").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const paymentTransactionsTable = pgTable("payment_transactions", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull(),
  subscriptionId: integer("subscription_id"),
  referenceNo: text("reference_no").notNull(),
  paynetTransactionId: text("paynet_transaction_id"),
  amount: real("amount").notNull(),
  currency: text("currency").notNull().default("TRY"),
  status: text("status").notNull().default("pending"),
  type: text("type").notNull().default("charge"),
  plan: text("plan"),
  description: text("description"),
  cardMasked: text("card_masked"),
  cardHolder: text("card_holder"),
  bankName: text("bank_name"),
  authorizationCode: text("authorization_code"),
  errorMessage: text("error_message"),
  paynetSessionId: text("paynet_session_id"),
  paynetTokenId: text("paynet_token_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
